<Project Sdk="NeoRune.Sdk/0.3.1">
  <PropertyGroup>
    <NeoRuneInstall>false</NeoRuneInstall>
    <NeoRuneModName>MCD2CombatBridge</NeoRuneModName>
    <Nullable>annotations</Nullable>
    <Version>1.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../bindings/combat/combat-bindings.csproj" />
  </ItemGroup>
</Project>
