// SPDX-License-Identifier: MIT
// 白名单由本地敌人资源 Type 字段生成，仅用于物品来源识别。
// 已核实的装备掉落来源白名单。
static class EquipmentDropOrigins
{
    // 查询已核实白名单；未知值不自动放行。
    public static bool Known(string source)
    {
        switch (source)
        {
            case "SW.Mob.BabySentinel":
            case "SW.Mob.BabySentinel.SoulStated":
            case "SW.Mob.BabyZombie":
            case "SW.Mob.BabyZombie.SoulStated":
            case "SW.Mob.BabyZombieSoulImbalance":
            case "SW.Mob.Bee.Honeypot":
            case "SW.Mob.Bloombud":
            case "SW.Mob.Bloombud.SoulStated":
            case "SW.Mob.BloombudSoulImbalance":
            case "SW.Mob.Bonker":
            case "SW.Mob.Bonker.SoulStated":
            case "SW.Mob.Camo":
            case "SW.Mob.CaveSpider":
            case "SW.Mob.CaveSpider.SoulStated":
            case "SW.Mob.Chicken.Jockey":
            case "SW.Mob.Chicken.Jockey.SoulStated":
            case "SW.Mob.CopperCube":
            case "SW.Mob.Cow":
            case "SW.Mob.Creeper":
            case "SW.Mob.Creeper.SoulStated":
            case "SW.Mob.CreeperCharged":
            case "SW.Mob.CrestedSentinel":
            case "SW.Mob.CrestedSentinel.SoulStated":
            case "SW.Mob.DeepDarkGolem":
            case "SW.Mob.DeepDarkGolem.SoulStated":
            case "SW.Mob.DeepDarkIllager":
            case "SW.Mob.DeepDarkIllager.BackpackVariant":
            case "SW.Mob.DeepDarkIllager.BackpackVariant.SoulStated":
            case "SW.Mob.DeepDarkIllager.SoulStated":
            case "SW.Mob.Default.Hostile":
            case "SW.Mob.Default.MeleeAttackMob":
            case "SW.Mob.Default.MeleeAttackMob.Heavy":
            case "SW.Mob.Default.Passive":
            case "SW.Mob.Default.RangedAttackMob":
            case "SW.Mob.Default.Type2":
            case "SW.Mob.Default.Type3":
            case "SW.Mob.Default.UnkillablePanicMob":
            case "SW.Mob.Driftweaver":
            case "SW.Mob.Driftweaver.SoulStated":
            case "SW.Mob.Enchanter":
            case "SW.Mob.Enchanter.SoulStated":
            case "SW.Mob.Enderman":
            case "SW.Mob.Enderman.SoulStated":
            case "SW.Mob.Evoker":
            case "SW.Mob.Evoker.SoulStated":
            case "SW.Mob.FloatySentinel":
            case "SW.Mob.FloatySentinel.SoulStated":
            case "SW.Mob.Fox":
            case "SW.Mob.FrostbiteDesertBoss":
            case "SW.Mob.Geomancer":
            case "SW.Mob.Geomancer.SoulStated":
            case "SW.Mob.Goat":
            case "SW.Mob.GrooblerSentinel":
            case "SW.Mob.GrooblerSentinel.SoulStated":
            case "SW.Mob.Herd":
            case "SW.Mob.Husk":
            case "SW.Mob.Husk.SoulStated":
            case "SW.Mob.JellyBunnySoulEngorged":
            case "SW.Mob.Llama":
            case "SW.Mob.Maw":
            case "SW.Mob.Monstrosity":
            case "SW.Mob.Monstrosity.Copper":
            case "SW.Mob.Monstrosity.Copper.Storm":
            case "SW.Mob.Monstrosity.Moss":
            case "SW.Mob.Monstrosity.Moss.Storm":
            case "SW.Mob.Monstrosity.RedStone":
            case "SW.Mob.Monstrosity.RedStone.Storm":
            case "SW.Mob.Monstrosity.Sculk":
            case "SW.Mob.Monstrosity.Sculk.Storm":
            case "SW.Mob.Monstrosity.Storm":
            case "SW.Mob.MossCube":
            case "SW.Mob.Pig":
            case "SW.Mob.PiggyBank":
            case "SW.Mob.Pillager":
            case "SW.Mob.Pillager.SoulStated":
            case "SW.Mob.PillagerVariant1":
            case "SW.Mob.PillagerVariant1.SoulStated":
            case "SW.Mob.PillagerVariant2":
            case "SW.Mob.PillagerVariant2.SoulStated":
            case "SW.Mob.Prickle":
            case "SW.Mob.Pufflet":
            case "SW.Mob.Pufflet.SoulStated":
            case "SW.Mob.Ravager":
            case "SW.Mob.Ravager.SoulStated":
            case "SW.Mob.Ravager.WithRider":
            case "SW.Mob.Ravager.WithRider.SoulStated":
            case "SW.Mob.RedStoneCube":
            case "SW.Mob.Roamroot":
            case "SW.Mob.Roamroot.SoulStated":
            case "SW.Mob.RoamrootSoulImbalance":
            case "SW.Mob.RoyalGuard":
            case "SW.Mob.RoyalGuard.SoulStated":
            case "SW.Mob.ScavengerGrappler":
            case "SW.Mob.ScavengerGrappler.SoulStated":
            case "SW.Mob.ScavengerMelee":
            case "SW.Mob.ScavengerMelee.SoulStated":
            case "SW.Mob.ScavengerMeleeSoulImbalance":
            case "SW.Mob.ScavengerRanged":
            case "SW.Mob.ScavengerRanged.SoulStated":
            case "SW.Mob.ScavengerRangedSoulImbalance":
            case "SW.Mob.ScavengerTrapper":
            case "SW.Mob.ScavengerTrapper.SoulStated":
            case "SW.Mob.SculkCube":
            case "SW.Mob.Shade":
            case "SW.Mob.Shade.Clone":
            case "SW.Mob.Sheep":
            case "SW.Mob.Skeleton":
            case "SW.Mob.Skeleton.SoulStated":
            case "SW.Mob.SkeletonCharred":
            case "SW.Mob.SkeletonLongRange":
            case "SW.Mob.SkeletonMossy":
            case "SW.Mob.SkeletonSoulimbalance":
            case "SW.Mob.SkeletonStray":
            case "SW.Mob.SkeletonVariant1":
            case "SW.Mob.SkeletonVariant1.SoulStated":
            case "SW.Mob.SkeletonVariant2":
            case "SW.Mob.SkeletonVariant2.SoulStated":
            case "SW.Mob.Slime":
            case "SW.Mob.Slime.SoulStated":
            case "SW.Mob.SlimeMedium":
            case "SW.Mob.SlimeMedium.SoulStated":
            case "SW.Mob.SlimeSmall":
            case "SW.Mob.SlimeSmall.SoulStated":
            case "SW.Mob.SnowFox":
            case "SW.Mob.SoulConstruct":
            case "SW.Mob.Spider":
            case "SW.Mob.Spider.Jockey":
            case "SW.Mob.Spider.Jockey.SoulStated":
            case "SW.Mob.Spider.SoulStated":
            case "SW.Mob.SpiderSoulImbalance":
            case "SW.Mob.SupremeEvoker":
            case "SW.Mob.TargetDummy":
            case "SW.Mob.Vanguard":
            case "SW.Mob.Vanguard.SoulStated":
            case "SW.Mob.Variant.Level1":
            case "SW.Mob.Vex":
            case "SW.Mob.Vex.SoulStated":
            case "SW.Mob.Vindicator":
            case "SW.Mob.Vindicator.SoulStated":
            case "SW.Mob.VindicatorVariant1":
            case "SW.Mob.VindicatorVariant1.SoulStated":
            case "SW.Mob.VindicatorVariant2":
            case "SW.Mob.VindicatorVariant2.SoulStated":
            case "SW.Mob.Warden":
            case "SW.Mob.Warden.SoulStated":
            case "SW.Mob.WellspringMiniboss":
            case "SW.Mob.WellspringMiniboss.SoulStated":
            case "SW.Mob.WildSentinel":
            case "SW.Mob.WildSentinel.SoulStated":
            case "SW.Mob.Witch":
            case "SW.Mob.Witch.SoulStated":
            case "SW.Mob.Witch.Type3":
            case "SW.Mob.WitchSlime":
            case "SW.Mob.WitchSlime.SoulStated":
            case "SW.Mob.Wobble":
            case "SW.Mob.Wolf":
            case "SW.Mob.Wolf.Woods":
            case "SW.Mob.Zombie":
            case "SW.Mob.Zombie.SoulStated":
            case "SW.Mob.ZombieCharred":
            case "Sw.Mob.ZombieFrozen":
            case "SW.Mob.ZombieMossy":
            case "SW.Mob.ZombieSoulimbalance":
            case "SW.Mob.ZombieVariant1":
            case "SW.Mob.ZombieVariant1.SoulStated":
            case "SW.Mob.ZombieVariant2":
            case "SW.Mob.ZombieVariant2.SoulStated":
                return true;
        }

        return false;
    }
}
